// Optional Claude Code router hook (project scope). Plans before writing; settings.json must be
// strict JSON (Claude Code rejects comments), otherwise the install stops with a conflict.
import fs from "node:fs";
import path from "node:path";
import { exists, sha256, writeFileAtomic } from "./fsx.mjs";

export const HOOK_MARKER = "Context Window — Claude Code Skill Router Hook";
export const HOOK_COMMAND =
  'node "$CLAUDE_PROJECT_DIR/.claude/hooks/skill-router.mjs"';

export function hookFiles(target) {
  const claudeDir = path.join(target, ".claude");
  return {
    script: path.join(claudeDir, "hooks", "skill-router.mjs"),
    routing: path.join(claudeDir, "skill-routing.json"),
    settings: path.join(claudeDir, "settings.json"),
  };
}

export function buildRoutingEntries(skills, scopeLabel) {
  return skills
    .filter((s) => (s.triggers ?? []).length)
    .map((s) => ({
      cw: true,
      skill: s.id,
      hint: s.summary ?? "",
      skillPath: `${scopeLabel}/${s.id}/SKILL.md`,
      ...(s.mandatory ? { mandatory: true } : {}),
      promptTriggers: s.triggers,
    }));
}

function isOurRegistration(hook) {
  return (
    typeof hook?.command === "string" &&
    hook.command.includes(".claude/hooks/skill-router.mjs")
  );
}

/**
 * @returns {{actions: Array<{file: string, next: string|null}>, conflicts: string[]}}
 */
export function planHook({
  target,
  template,
  entries,
  remove,
  previousScriptHash,
  forceLocal,
}) {
  const files = hookFiles(target);
  const actions = [];
  const conflicts = [];

  if (exists(files.script)) {
    const current = fs.readFileSync(files.script, "utf8");
    if (!current.includes(HOOK_MARKER))
      conflicts.push(
        `${files.script} exists and is not managed by Context Window`,
      );
    else if (
      previousScriptHash &&
      sha256(current) !== previousScriptHash &&
      !forceLocal
    )
      conflicts.push(`${files.script} was edited locally`);
    else if (remove) actions.push({ file: files.script, next: null });
    else if (current !== template)
      actions.push({ file: files.script, next: template });
  } else if (!remove) {
    actions.push({ file: files.script, next: template });
  }

  let routing = { skills: [] };
  if (exists(files.routing)) {
    try {
      routing = JSON.parse(fs.readFileSync(files.routing, "utf8"));
      if (!Array.isArray(routing.skills))
        throw new Error("skills must be an array");
    } catch (error) {
      conflicts.push(
        `${files.routing} is not valid routing JSON (${error.message})`,
      );
    }
  }
  const userEntries = (routing.skills ?? []).filter((e) => e?.cw !== true);
  const nextRouting = {
    $comment:
      'Entries with "cw": true are generated by Context Window and replaced on update. Other entries belong to this project and are preserved.',
    skills: [...(remove ? [] : entries), ...userEntries],
  };
  if (remove && !userEntries.length) {
    if (exists(files.routing))
      actions.push({ file: files.routing, next: null });
  } else {
    const text = `${JSON.stringify(nextRouting, null, 2)}\n`;
    if (
      !exists(files.routing) ||
      fs.readFileSync(files.routing, "utf8") !== text
    )
      actions.push({ file: files.routing, next: text });
  }

  let settings = {};
  if (exists(files.settings)) {
    try {
      settings = JSON.parse(fs.readFileSync(files.settings, "utf8"));
    } catch (error) {
      conflicts.push(
        `${files.settings} is not strict JSON (${error.message.split("\n")[0]}); Claude Code requires strict JSON, fix it before installing the hook`,
      );
    }
  }
  const hooks = { ...(settings.hooks ?? {}) };
  const current = Array.isArray(hooks.UserPromptSubmit)
    ? hooks.UserPromptSubmit
    : [];
  const withoutOurs = current
    .map((group) => ({
      ...group,
      hooks: (group.hooks ?? []).filter((h) => !isOurRegistration(h)),
    }))
    .filter((group) => group.hooks.length);
  const ours = {
    hooks: [
      {
        type: "command",
        command: `${HOOK_COMMAND} UserPromptSubmit`,
        timeout: 15,
      },
    ],
  };
  hooks.UserPromptSubmit = remove ? withoutOurs : [...withoutOurs, ours];
  if (!hooks.UserPromptSubmit.length) delete hooks.UserPromptSubmit;
  for (const event of Object.keys(hooks)) {
    if (event === "UserPromptSubmit" || !Array.isArray(hooks[event])) continue;
    const cleaned = hooks[event]
      .map((group) => ({
        ...group,
        hooks: (group.hooks ?? []).filter((h) => !isOurRegistration(h)),
      }))
      .filter((group) => group.hooks.length);
    if (cleaned.length) hooks[event] = cleaned;
    else delete hooks[event];
  }
  const nextSettings = { ...settings, hooks };
  if (!Object.keys(hooks).length) delete nextSettings.hooks;
  const settingsText = `${JSON.stringify(nextSettings, null, 2)}\n`;
  const currentText = exists(files.settings)
    ? fs.readFileSync(files.settings, "utf8")
    : null;
  if (currentText !== settingsText && !(remove && currentText === null)) {
    actions.push({
      file: files.settings,
      next: Object.keys(nextSettings).length ? settingsText : null,
    });
  }
  return { actions, conflicts, scriptHash: sha256(template) };
}

export function applyHook(planned) {
  for (const action of planned.actions) {
    if (action.next === null) {
      if (exists(action.file)) fs.unlinkSync(action.file);
    } else {
      writeFileAtomic(action.file, action.next);
    }
  }
}

export function hookState(target, template) {
  const files = hookFiles(target);
  const state = { script: "absent", registered: false };
  if (exists(files.script))
    state.script =
      fs.readFileSync(files.script, "utf8") === template
        ? "current"
        : "different";
  try {
    const settings = JSON.parse(fs.readFileSync(files.settings, "utf8"));
    state.registered = (settings.hooks?.UserPromptSubmit ?? []).some((g) =>
      (g.hooks ?? []).some(isOurRegistration),
    );
  } catch {
    state.registered = false;
  }
  return state;
}
